name: 'Wait-For-Other-Pipelines'
description: 'Wait for other pipelines'
branding:
  icon: pause
  color: purple
inputs:
  step_name:  # id of input
    description: 'Step Name'
    required: true
runs:
  using: "composite"
  steps:
    - run: bash wait.sh "${{ inputs.step_name }}"
      shell: bash
