name: 'Wait-For-Other-Pipelines'
description: 'Wait for other pipelines'
branding:
  icon: pause
  color: purple
inputs:
  step_name:
    description: 'Step Name'
    required: true
runs: 
  using: 'docker'
  image: 'Dockerfile'
  
